for(let i =1;i <= 10; i++){
    console.log(`Valor de i(bucle externo):${i}`)
    for(let j =0;j <= i; j++){
        console.log(`         Valor de i(bucle interno):${j}`)
    }
}

// Valor de i(bucle externo):1
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
// Valor de i(bucle externo):2
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
// Valor de i(bucle externo):3
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
//          Valor de i(bucle interno):3
// Valor de i(bucle externo):4
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
//          Valor de i(bucle interno):3
//          Valor de i(bucle interno):4
// Valor de i(bucle externo):5
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
//          Valor de i(bucle interno):3
//          Valor de i(bucle interno):4
//          Valor de i(bucle interno):5
// Valor de i(bucle externo):6
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
//          Valor de i(bucle interno):3
//          Valor de i(bucle interno):4
//          Valor de i(bucle interno):5
//          Valor de i(bucle interno):6
// Valor de i(bucle externo):7
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
//          Valor de i(bucle interno):3
//          Valor de i(bucle interno):4
//          Valor de i(bucle interno):5
//          Valor de i(bucle interno):6
//          Valor de i(bucle interno):7
// Valor de i(bucle externo):8
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
//          Valor de i(bucle interno):3
//          Valor de i(bucle interno):4
//          Valor de i(bucle interno):5
//          Valor de i(bucle interno):6
//          Valor de i(bucle interno):7
//          Valor de i(bucle interno):8
// Valor de i(bucle externo):9
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
//          Valor de i(bucle interno):3
//          Valor de i(bucle interno):4
//          Valor de i(bucle interno):5
//          Valor de i(bucle interno):6
//          Valor de i(bucle interno):7
//          Valor de i(bucle interno):8
//          Valor de i(bucle interno):9
// Valor de i(bucle externo):10
//          Valor de i(bucle interno):0
//          Valor de i(bucle interno):1
//          Valor de i(bucle interno):2
//          Valor de i(bucle interno):3
//          Valor de i(bucle interno):4
//          Valor de i(bucle interno):5
//          Valor de i(bucle interno):6
//          Valor de i(bucle interno):7
//          Valor de i(bucle interno):8
//          Valor de i(bucle interno):9
//          Valor de i(bucle interno):10